In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [3]:
file = pd.read_csv("customer_shopping_behavior.csv")
file.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [4]:
file.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [6]:
file.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [8]:
file.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [12]:
file['Review Rating'] = file['Review Rating'].fillna(file.groupby('Category')['Review Rating'].transform('median'))

In [14]:
file.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3900 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [16]:
#verifying whether Promo Code Used and Discount Applied are truly identical
pd.crosstab(file['Promo Code Used'],file['Discount Applied'])

Discount Applied    No   Yes
Promo Code Used
No                2223     0
Yes                  0  1677

In [17]:
#drop column Promo Code Used
file.drop(columns = ['Promo Code Used'],inplace=True)

In [18]:
file.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3900 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Previous Purchases      3900 non-null   int64
 15  Payment Method          3900 non-null   object
 16  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(12)
memory usage: 518.1+ KB

In [19]:
#change column name writing style
file.columns = file.columns.str.lower()
file.columns = file.columns.str.replace(' ', '_')

In [23]:
file.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   customer_id             3900 non-null   int64
 1   age                     3900 non-null   int64
 2   gender                  3900 non-null   object
 3   item_purchased          3900 non-null   object
 4   category                3900 non-null   object
 5   purchase_amount_(usd)   3900 non-null   int64
 6   location                3900 non-null   object
 7   size                    3900 non-null   object
 8   color                   3900 non-null   object
 9   season                  3900 non-null   object
 10  review_rating           3900 non-null   float64
 11  subscription_status     3900 non-null   object
 12  shipping_type           3900 non-null   object
 13  discount_applied        3900 non-null   object
 14  previous_purchases      3900 non-null   int64
 15  payment_method          3900 non-null   object
 16  frequency_of_purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(12)
memory usage: 518.1+ KB

In [24]:
file.columns = file.columns.str.replace('(usd)','usd')

In [25]:
file.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   customer_id             3900 non-null   int64
 1   age                     3900 non-null   int64
 2   gender                  3900 non-null   object
 3   item_purchased          3900 non-null   object
 4   category                3900 non-null   object
 5   purchase_amount_usd     3900 non-null   int64
 6   location                3900 non-null   object
 7   size                    3900 non-null   object
 8   color                   3900 non-null   object
 9   season                  3900 non-null   object
 10  review_rating           3900 non-null   float64
 11  subscription_status     3900 non-null   object
 12  shipping_type           3900 non-null   object
 13  discount_applied        3900 non-null   object
 14  previous_purchases      3900 non-null   int64
 15  payment_method          3900 non-null   object
 16  frequency_of_purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(12)
memory usage: 518.1+ KB

In [26]:
#create a column age_group
labels = ['young adult','adult','middle aged','senior']
file['age_group'] = pd.qcut(file['age'],q = 4, labels = labels)

In [31]:
file.head()

,customer_id,age,gender,item_purchased,category,purchase_amount_usd,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,middle aged
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,young adult
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,middle aged
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,young adult
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,middle aged

In [32]:
file['frequency_of_purchases'].unique()

array(['Fortnightly', 'Weekly', 'Annually', 'Quarterly', 'Bi-Weekly',
       'Monthly', 'Every 3 Months'], dtype=object)

In [33]:
#create new column purchase frequency days
frequency_mapping =     {
    'Fortnightly': 14,
    'Weekly' : 7,
    'Annually' : 365,
    'Quarterly' : 90,
    'Bi-Weekly' : 14,
    'Monthly': 30,
    'Every 3 Months': 90
                        }

In [34]:
file['purchase_frequency_days'] = file['frequency_of_purchases'].map(frequency_mapping)

In [36]:
file['purchase_frequency_days']

0        14
1        14
2         7
3         7
4       365
       ...
3895      7
3896     14
3897     90
3898      7
3899     90
Name: purchase_frequency_days, Length: 3900, dtype: int64

In [37]:
file.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 19 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   customer_id              3900 non-null   int64
 1   age                      3900 non-null   int64
 2   gender                   3900 non-null   object
 3   item_purchased           3900 non-null   object
 4   category                 3900 non-null   object
 5   purchase_amount_usd      3900 non-null   int64
 6   location                 3900 non-null   object
 7   size                     3900 non-null   object
 8   color                    3900 non-null   object
 9   season                   3900 non-null   object
 10  review_rating            3900 non-null   float64
 11  subscription_status      3900 non-null   object
 12  shipping_type            3900 non-null   object
 13  discount_applied         3900 non-null   object
 14  previous_purchases       3900 non-null   int64
 15  payment_method           3900 non-null   object
 16  frequency_of_purchases   3900 non-null   object
 17  age_group                3900 non-null   category
 18  purchase_frequency_days  3900 non-null   int64
dtypes: category(1), float64(1), int64(5), object(12)
memory usage: 552.6+ KB

In [38]:
file_copy = file.copy()

In [43]:
#delete column frequency_of_purchases
file_copy = file_copy.drop('frequency_of_purchases',axis = 1)

In [45]:
file_copy.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_usd', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method', 'age_group',
       'purchase_frequency_days'],
      dtype='object')

In [46]:
pip install jupysql psycopg2-binary sqlalchemy

Collecting jupysql
  Downloading jupysql-0.11.1-py3-none-any.whl.metadata (5.9 kB)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.12-cp313-cp313-win_amd64.whl.metadata (5.1 kB)
Requirement already satisfied: sqlalchemy in c:\users\ragikrishna\anaconda3\lib\site-packages (2.0.43)
Collecting prettytable>=3.12.0 (from jupysql)
  Downloading prettytable-3.17.0-py3-none-any.whl.metadata (34 kB)
Collecting sqlparse (from jupysql)
  Downloading sqlparse-0.5.5-py3-none-any.whl.metadata (4.7 kB)
Collecting ipython-genutils>=0.1.0 (from jupysql)
  Downloading ipython_genutils-0.2.0-py2.py3-none-any.whl.metadata (755 bytes)
Requirement already satisfied: jinja2 in c:\users\ragikrishna\anaconda3\lib\site-packages (from jupysql) (3.1.6)
Collecting sqlglot>=11.3.7 (from jupysql)
  Downloading sqlglot-30.7.0-py3-none-any.whl.metadata (24 kB)
Collecting jupysql-plugin>=0.4.2 (from jupysql)
  Downloading jupysql_plugin-0.4.5-py3-none-any.whl.metadata (7.8 kB)
Collecting ploomber-core>=0.2.7 (from jupysql)
  Downloading ploomber_core-0.2.27-py3-none-any.whl.metadata (532 bytes)
Requirement already satisfied: greenlet>=1 in c:\users\ragikrishna\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\ragikrishna\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: pyyaml in c:\users\ragikrishna\anaconda3\lib\site-packages (from ploomber-core>=0.2.7->jupysql) (6.0.3)
Collecting posthog>=3.0 (from ploomber-core>=0.2.7->jupysql)
  Downloading posthog-7.14.1-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: requests<3.0,>=2.7 in c:\users\ragikrishna\anaconda3\lib\site-packages (from posthog>=3.0->ploomber-core>=0.2.7->jupysql) (2.32.5)
Collecting backoff>=1.10.0 (from posthog>=3.0->ploomber-core>=0.2.7->jupysql)
  Downloading backoff-2.2.1-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: distro>=1.5.0 in c:\users\ragikrishna\anaconda3\lib\site-packages (from posthog>=3.0->ploomber-core>=0.2.7->jupysql) (1.9.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\ragikrishna\anaconda3\lib\site-packages (from requests<3.0,>=2.7->posthog>=3.0->ploomber-core>=0.2.7->jupysql) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\ragikrishna\anaconda3\lib\site-packages (from requests<3.0,>=2.7->posthog>=3.0->ploomber-core>=0.2.7->jupysql) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\ragikrishna\anaconda3\lib\site-packages (from requests<3.0,>=2.7->posthog>=3.0->ploomber-core>=0.2.7->jupysql) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\ragikrishna\anaconda3\lib\site-packages (from requests<3.0,>=2.7->posthog>=3.0->ploomber-core>=0.2.7->jupysql) (2025.11.12)
Requirement already satisfied: wcwidth in c:\users\ragikrishna\appdata\roaming\python\python313\site-packages (from prettytable>=3.12.0->jupysql) (0.6.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\ragikrishna\anaconda3\lib\site-packages (from jinja2->jupysql) (3.0.2)
Downloading jupysql-0.11.1-py3-none-any.whl (95 kB)
Downloading psycopg2_binary-2.9.12-cp313-cp313-win_amd64.whl (2.8 MB)
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ----------- ---------------------------- 0.8/2.8 MB 3.4 MB/s eta 0:00:01
   ---------------------------------- ----- 2.4/2.8 MB 5.1 MB/s eta 0:00:01
   ---------------------------------------- 2.8/2.8 MB 5.2 MB/s  0:00:00
Downloading ipython_genutils-0.2.0-py2.py3-none-any.whl (26 kB)
Downloading jupysql_plugin-0.4.5-py3-none-any.whl (192 kB)
Downloading ploomber_core-0.2.27-py3-none-any.whl (22 kB)
Downloading posthog-7.14.1-py3-none-any.whl (240 kB)
Downloading backoff-2.2.1-py3-none-any.whl (15 kB)
Downloading prettytable-3.17.0-py3-none-any.whl (34 kB)
Downloading sqlglot-30.7.0-py3-none-any.whl (683 kB)
   ---------------------------------------- 0.0/683.6 kB ? eta -:--:--
   ---------------------------------------- 683.6/683.6 kB 7.2 MB/s  0:00:00
Downloading sqlparse-0.5.5-py3-none-any.whl (46 kB)
Installing collected packages: ipython-genutils, sqlparse, sqlglot, psycopg2-binary, prettytable, backoff, posthog, ploomber-core, jupysql-plugin, jupysql

   ---- -----------------------------------  1/10 [sqlparse]
   ---- -----------------------------------  1/10 [sqlparse]
   -------- -------------------------------  2/10 [sqlglot]
   -------- -------------------------------  2/10 [sqlglot]
   -------- -------------------------------  2/10 [sqlglot]
   -------- -------------------------------  2/10 [sqlglot]
   -------- -------------------------------  2/10 [sqlglot]
   -------- -------------------------------  2/10 [sqlglot]
   -------- -------------------------------  2/10 [sqlglot]
   -------- -------------------------------  2/10 [sqlglot]
   -------- -------------------------------  2/10 [sqlglot]
   -------- -------------------------------  2/10 [sqlglot]
   -------- -------------------------------  2/10 [sqlglot]
   -------- -------------------------------  2/10 [sqlglot]
   ------------ ---------------------------  3/10 [psycopg2-binary]
   ------------ ---------------------------  3/10 [psycopg2-binary]
   ---------------- -----------------------  4/10 [prettytable]
   ------------------------ ---------------  6/10 [posthog]
   ------------------------ ---------------  6/10 [posthog]
   ------------------------ ---------------  6/10 [posthog]
   ------------------------ ---------------  6/10 [posthog]
   ------------------------ ---------------  6/10 [posthog]
   ------------------------ ---------------  6/10 [posthog]
   ---------------------------- -----------  7/10 [ploomber-core]
   ------------------------------------ ---  9/10 [jupysql]
   ------------------------------------ ---  9/10 [jupysql]
   ------------------------------------ ---  9/10 [jupysql]
   ---------------------------------------- 10/10 [jupysql]

Successfully installed backoff-2.2.1 ipython-genutils-0.2.0 jupysql-0.11.1 jupysql-plugin-0.4.5 ploomber-core-0.2.27 posthog-7.14.1 prettytable-3.17.0 psycopg2-binary-2.9.12 sqlglot-30.7.0 sqlparse-0.5.5
Note: you may need to restart the kernel to use updated packages.

In [3]:
%load_ext sql

In [4]:
%sql postgresql://postgres:admin1234@localhost/customer_behaviour

Connecting to 'postgresql://postgres:***@localhost/customer_behaviour'

In [5]:
engine = create_engine('postgresql://postgres:admin1234@localhost:5432/customer_behaviour')

In [54]:
file_copy.to_sql('customer_behaviour',engine,if_exists = 'replace',index=False)

900